DATABASE = '/tmp/gus.db'
DEBUG = True
SECRET_KEY = 'devkey'
USERNAME = 'admin'
PASSWORD = 'default'

RECAPTCHA_USE_SSL = False
RECAPTCHA_PUBLIC_KEY = "6LfNKOESAAAAAOvRghdScTPfOC9PNpYNmpkIqbUn"
RECAPTCHA_PRIVATE_KEY = "6LfNKOESAAAAAFGnwNgYtDl-BEaanP_XWWzLd4rO"
